name: Update Veille
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install
        run: pip install feedparser google-generativeai
      - name: Run
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python script.py
      - name: Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html
          git commit -m "update" || exit 0
          git push
